name: First_action_raul
on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: echo "Hello world!"

jobs:
  bye-world:
    runs-on: ubuntu-latest
    steps:
      - name: Bye Step
        run: echo "bye world!"