name: First_action_raul
on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: echo "Hello world!"


  bye-world:
    runs-on: ubuntu-latest
    needs: hello-world
    steps:
      - name: Bye Step
        run: echo "bye world!"