name: run_python

on:
  push:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        -name: Set up Python
        uses: actions/setup-python@v4
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r code/python/requirements.txt
        
        name: Run security check
        run: bandit -r code/python